# -*- coding: utf-8 -*-
"""世界人口地图.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yxSF527NOVtbXzR8lM4lTDsWtzlmgiCf
"""

import json
import pygal.maps.world
from pygal_maps_world import i18n

filename = 'population_json.json'


def get_country_code(country_name):
    for code, name in i18n.COUNTRIES.items():
        if name == country_name:
            return code
    return None


with open(filename) as f:
    pop_data = json.load(f)
cc_population = {}
for pop_dict in pop_data:
    if pop_dict['Year'] == 2010:
        country_name = pop_dict['Country Name']
        population = int(pop_dict['Value'])
        code = get_country_code(country_name)
        if code:
            cc_population[code] = population
cc_pops_1, cc_pops_2, cc_pops_3 = {}, {}, {}
for cc, pop in cc_population.items():
    if pop < 10000000:
        cc_pops_1[cc] = pop
    elif pop < 1000000000:
        cc_pops_2[cc] = pop
    else:
        cc_pops_3[cc] = pop
print(len(cc_pops_1), len(cc_pops_2), len(cc_pops_3))
wm = pygal.maps.world.World()
wm.title = 'World Population in 2010, by Country'
wm.add('0-10m', cc_pops_1)
wm.add('10m-1bn', cc_pops_2)
wm.add('>1bn', cc_pops_3)
wm.render_to_file('americas.svg')
