# -*- coding: utf-8 -*-
"""下载数据

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11_7T0_CszBInePIGT6-oaqpJEDw98Vi_
"""

import csv
filename = '文件.csv'
with open(filename) as f:
  reader = csv.reader(f)
  header_row = next(reader)
  for index, column_header in enumerate(header_row):
    print(index, column_header)
  highs = []
  for row in reader:
    highs.append(row[1])
  print(highs)

import csv
import matplotlib.pyplot as plt
filename = '文件1.csv'
with open(filename) as f:
  reader = csv.reader(f)
  header_row = next(reader)
  highs = []
  for row in reader:
    high = int(row[1])
    highs.append(high)
  print(highs)
plt.figure(figsize = (10, 5))
plt.plot(highs, c = 'r')
plt.title('hello',fontsize = 40)
plt.xlabel('', fontsize = 20)
plt.ylabel('Temperature(F)', fontsize = 20)
plt.tick_params(axis = 'both', which = 'major', labelsize = 20)
plt.show()

import csv
from datetime import datetime
import matplotlib.pyplot as plt
filename = '文件2.csv'
with open(filename) as f:
  reader = csv.reader(f)
  header_row = next(reader)
  dates, highs = [], []
  for row in reader:
    current_date = datetime.strptime(row[0], '%Y/%m/%d')
    dates.append(current_date)
    high = int(row[1])
    highs.append(high)
fig = plt.figure(figsize = (10, 6))
plt.plot(dates, highs, c = 'r')
plt.title('hello', fontsize = 40)
plt.xlabel('', fontsize = 20)
fig.autofmt_xdate() # 让x轴的刻度日期斜着写
plt.ylabel('Temperature(F)', fontsize = 20)
plt.tick_params(axis = 'both', which = 'major', labelsize = 20)
plt.show()

import csv
from datetime import datetime
import matplotlib.pyplot as plt
filename = '文件2.csv'
with open(filename) as f:
  reader = csv.reader(f)
  header_row = next(reader)
  dates, highs, lows = [], [], []
  for row in reader:
    current_date = datetime.strptime(row[0], '%Y/%m/%d')
    dates.append(current_date)
    high = int(row[1])
    highs.append(high)
    low = int(row[2])
    lows.append(low)
fig = plt.figure(figsize = (10, 6))
plt.plot(dates, highs, c = 'r', alpha = 0.5) # alpha为透明度
plt.title('hello', fontsize = 40, alpha = 0.5)
plt.fill_between(dates, highs, lows, facecolor = 'Blue', alpha = 0.1)
plt.xlabel('', fontsize = 20)
fig.autofmt_xdate() # 让x轴的刻度日期斜着写
plt.ylabel('Temperature(F)', fontsize = 20)
plt.tick_params(axis = 'both', which = 'major', labelsize = 20)
plt.show()

import csv
from datetime import datetime
import matplotlib.pyplot as plt
filename = '文件3.csv'
with open(filename) as f:
  reader = csv.reader(f)
  header_row = next(reader)
  dates, highs, lows = [], [], []
  for row in reader:
    try:
      current_date = datetime.strptime(row[0], '%Y/%m/%d')
      high = int(row[1])
      low = int(row[2])
    except ValueError:
      print(current_date, 'missing data')
    else:
      dates.append(current_date)
      highs.append(high)
      lows.append(low)
fig = plt.figure(figsize = (10, 6))
plt.plot(dates, highs, c = 'r', alpha = 0.5) # alpha为透明度
plt.title('hello', fontsize = 40, alpha = 0.5)
plt.fill_between(dates, highs, lows, facecolor = 'Blue', alpha = 0.1)
plt.xlabel('', fontsize = 20)
fig.autofmt_xdate() # 让x轴的刻度日期斜着写
plt.ylabel('Temperature(F)', fontsize = 20)
plt.tick_params(axis = 'both', which = 'major', labelsize = 20)
plt.show()
